// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function script39(){
//cartas que não usamos mais
/*
nums[i++] = ++z;
strings[j++] = "Bob o Berseker";
nums[i++] = 0;//STAGE
strings[j++] = "Berseker";//TYPE
nums[i++] = 12;//HP
strings[j++] = "ATAQUE: SOCO SELVAGEM";
strings[j++] = "Berseker prepara para dar um soco no seu oponente e causa  20 de dano ao o inimigo e gasta 50 de mana";
nums[i++] = 5;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 20;//damage
strings[j++] = "Ativa";
strings[j++] = ": Descarta 2 cartas para ganhar 20 de vida";
nums[i++] = 0;
nums[i++] = 0;
nums[i++] = 0;
strings[j++] = "Passiva";
strings[j++] = "Quando sua vida atinge 20, fica com um bônus de 4 de dano em todos os ataques";
nums[i++] = 0;
nums[i++] = 0;
nums[i++] = 0;
strings[j++] = "Guerreiro";
strings[j++] = "\0";
nums[i++] = 3; 
nums[i++] = 4;

//bob 2
nums[i++] = ++z;//card number
strings[j++] = "Bob o Berseker";//name
nums[i++] = 0;//stage
strings[j++] = "Berseker";//type
nums[i++] = 12;//hp
strings[j++] = "Golpe de Flail";//attack 1
strings[j++] = "Berseker gira seu flail e ataca seu  oponente e causa  30 de dano ao o inimigo e gasta 10 de mana";//attack desc
nums[i++] = 10;//type cost
nums[i++] = 2;//colorless cost
nums[i++] = 30;//damage
strings[j++] = "Ativa";
strings[j++] = ": Descarta 2 cartas para ganhar 20 de vida";
nums[i++] = 0;
nums[i++] = 0;
nums[i++] = 0;
strings[j++] = "Passiva";
strings[j++] = "Quando sua vida atinge 20, fica com um bônus de 4 de dano em todos os ataques";
nums[i++] = 0;
nums[i++] = 0;
nums[i++] = 0;
strings[j++] = "Guerreiro";
strings[j++] = "\0";
nums[i++] = 3; 
nums[i++] = 4;

//Bob3
nums[i++] = ++z;//card number
strings[j++] = "Bob o Berseker";//name
nums[i++] = 0;//stage
strings[j++] = "Berseker";//type
nums[i++] = 12;//hp
strings[j++] = "Raiva";//attack 1
strings[j++] = "Berseker está com raiva e avança no seu oponente causando  40 de dano ao o inimigo e gasta 30 de mana";//attack desc
nums[i++] = 30;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 40;//damage
strings[j++] = "Ativa";
strings[j++] = ": Descarta 2 cartas para ganhar 20 de vida";
nums[i++] = 0;
nums[i++] = 0;
nums[i++] = 0;
strings[j++] = "Passiva";
strings[j++] = "Quando sua vida atinge 20, fica com um bônus de 4 de dano em todos os ataques";
nums[i++] = 0;
nums[i++] = 0;
nums[i++] = 0;
strings[j++] = "Guerreiro";
strings[j++] = "\0";
nums[i++] = 3; 
nums[i++] = 4;

//AGUA
strings[j++] = "Bob o Berseker";//name
nums[i++] = 0;//stage
strings[j++] = "Berseker";//type
nums[i++] = 12;//hp
strings[j++] = "Clava de Ferro";//attack 1
strings[j++] = "Berseker ataca com sua clava  no seu oponente causando  60 de dano ao o inimigo e gasta 40 de mana";//attack desc
nums[i++] = 40;//type cost
nums[i++] = 1;//colorless cost
nums[i++] = 60;//damage
strings[j++] = "Ativa";
strings[j++] = ": Descarta 2 cartas para ganhar 20 de vida";
nums[i++] = 0;
nums[i++] = 0;
nums[i++] = 0;
strings[j++] = "Passiva";
strings[j++] = "Quando sua vida atinge 20, fica com um bônus de 4 de dano em todos os ataques";
nums[i++] = 0;
nums[i++] = 0;
nums[i++] = 0;
strings[j++] = "Guerreiro";
strings[j++] = "\0";
nums[i++] = 3; 
nums[i++] = 4;

//gyarados
nums[i++] = ++z;//card number
strings[j++] = "Bob o Berseker";//name
nums[i++] = 2;//stage
strings[j++] = "Berseker";//type
nums[i++] = 120;//hp
strings[j++] = "MACHADO";//attack 1
strings[j++] = "Berseker ataca com seu machado no seu oponente causando  100 de dano ao o inimigo e gasta 60 de mana";//attack desc
nums[i++] = 3;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 50;//damage
strings[j++] = "Ativa";
strings[j++] = ": Descarta 2 cartas para ganhar 20 de vida";
nums[i++] = 0;
nums[i++] = 0;
nums[i++] = 0;
strings[j++] = "Passiva";
strings[j++] = "Quando sua vida atinge 20, fica com um bônus de 4 de dano em todos os ataques";
nums[i++] = 0;
nums[i++] = 0;
nums[i++] = 0;
strings[j++] = "Guerreiro";
strings[j++] = "\0";
nums[i++] = 3; 
nums[i++] = 4;

//hitmonchan
nums[i++] = ++z;//card number
strings[j++] = "Bob o Berseker";//name
nums[i++] = 2;//stage
strings[j++] = "Berseker";//type
nums[i++] = 120;//hp
strings[j++] = "FORÇA BERSERKER";//attack 1
strings[j++] = "Berseker está fortalecido e avança no seu oponente causando 80 de dano ao o inimigo e gasta 50 de mana";//attack desc
nums[i++] = 50;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 80;//damage
strings[j++] = "Ativa";
strings[j++] = ": Descarta 2 cartas para ganhar 20 de vida";
nums[i++] = 0;
nums[i++] = 0;
nums[i++] = 0;
strings[j++] = "Passiva";
strings[j++] = "Quando sua vida atinge 20, fica com um bônus de 4 de dano em todos os ataques";
nums[i++] = 0;
nums[i++] = 0;
nums[i++] = 0;
strings[j++] = "Guerreiro";
strings[j++] = "\0";
nums[i++] = 3; 
nums[i++] = 4;
/item finder
nums[i++] = ++z;//card number
strings[j++] = "BUFF: FURIA BERSERKER ";//name
nums[i++] = 0;//stage
strings[j++] = "BUFF BERSEKER";//type
nums[i++] = 0;//hp
strings[j++] = "\0";//attack 1
strings[j++] = "Fique em modo berserker por 2 turnos e ganhe 20 dano extra. Gasta 80 de mana";//attack desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//attack 2
strings[j++] = "\0";//attack 2 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//attack 3
strings[j++] = "\0";//attack 3 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//weakness
strings[j++] = "\0";//resistance
nums[i++] = 0;//retreate cost
nums[i++] = 3;//rarity

//lass
nums[i++] = ++z;//card number
strings[j++] = "BUFF: SACRIFICIO DE SANGUE ";//name
nums[i++] = 0;//stage
strings[j++] = "BUFF BERSEKER";//type
nums[i++] = 0;//hp
strings[j++] = "\0";//attack 1
strings[j++] = "Sacrifique 50 de vida e 1 carta para ganhar 80 dano extra em seu proximo ataque. Gasta 100 de mana";//attack desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//attack 2
strings[j++] = "\0";//attack 2 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//attack 3
strings[j++] = "\0";//attack 3 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//weakness
strings[j++] = "\0";//resistance
nums[i++] = 0;//retreate cost
nums[i++] = 3;//rarity

//pokemon breeder
nums[i++] = ++z;//card number
strings[j++] = "BUFF: RITUAL DE SACRIFICIO";//name
nums[i++] = 0;//stage
strings[j++] = "BUFF BERSEKER";//type
nums[i++] = 0;//hp
strings[j++] = "\0";//attack 1
strings[j++] = "Sacrifique 1 carta de sua mão para, no próximo turno, você ter um bônus de 30 dano por 2 turnos. Gasta toda sua mana.";//attack desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//attack 2
strings[j++] = "\0";//attack 2 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//attack 3
strings[j++] = "\0";//attack 3 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//weakness
strings[j++] = "\0";//resistance
nums[i++] = 0;//retreate cost
nums[i++] = 3;//rarity

//joe
nums[i++] = ++z;//card number
strings[j++] = "Joe o Guerreiro";//name
nums[i++] = 0;//stage
strings[j++] = "Guerreiro";//type
nums[i++] = 180;//hp
strings[j++] = "ATAQUE: JOGUE SUA LANÇA ";//attack 1
strings[j++] = "O guerreiro joga sua lança causando 10 de dano gasta  10 de mana;"//attack desc
nums[i++] = 10;//type cost
nums[i++] = 2;//colorless cost
nums[i++] = 10;//damage
strings[j++] = "ATIVO";//attack 2
strings[j++] = "Ativa: Começa os turnos com 10 de vida a mais por ser valente.";//attack 2 desc
nums[i++] = 10;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "Passiva ";//attack 3
strings[j++] = "Passiva : Seus buff custam 10 de mana a menos.";//attack 3 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//weakness
strings[j++] = "\0";//resistance
nums[i++] = 3;//retreate cost
nums[i++] = 4;//rarity

nums[i++] = ++z;//card number
strings[j++] = "Joe o Guerreiro";//name
nums[i++] = 0;//stage
strings[j++] = "Guerreiro";//type
nums[i++] = 180;//hp
strings[j++] = "ATAQUE: ESCUDO VOADOR";//attack 1
strings[j++] = "O guerreiro joga sua seu escudo causando 30 de dano gasta 20 de mana;"//attack desc
nums[i++] = 20;//type cost
nums[i++] = 2;//colorless cost
nums[i++] = 30;//damage
strings[j++] = "ATIVO";//attack 2
strings[j++] = "Ativa: Começa os turnos com 10 de vida a mais por ser valente.";//attack 2 desc
nums[i++] = 10;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "Passiva ";//attack 3
strings[j++] = "Passiva : Seus buff custam 10 de mana a menos.";//attack 3 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//weakness
strings[j++] = "\0";//resistance
nums[i++] = 3;//retreate cost
nums[i++] = 4;//rarity


nums[i++] = ++z;//card number
strings[j++] = "Joe o Guerreiro";//name
nums[i++] = 0;//stage
strings[j++] = "Guerreiro";//type
nums[i++] = 180;//hp
strings[j++] = "ATAQUE: PRECISÃO ";//attack 1
strings[j++] = "O guerreiro entra em estado de foco e causa 40 de dano gasta 30 de mana"//attack desc
nums[i++] = 30;//type cost
nums[i++] = 2;//colorless cost
nums[i++] = 40;//damage
strings[j++] = "ATIVO";//attack 2
strings[j++] = "Ativa: Começa os turnos com 10 de vida a mais por ser valente.";//attack 2 desc
nums[i++] = 10;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "Passiva ";//attack 3
strings[j++] = "Passiva : Seus buff custam 10 de mana a menos.";//attack 3 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//weakness
strings[j++] = "\0";//resistance
nums[i++] = 3;//retreate cost
nums[i++] = 4;//rarity


nums[i++] = ++z;//card number
strings[j++] = "Joe o Guerreiro";//name
nums[i++] = 2;//stage
strings[j++] = "Guerreiro";//type
nums[i++] = 180;//hp
strings[j++] = "ATAQUE: CAVALO ";//attack 1
strings[j++] = " O cavalo do guerreiro avança no oponente  e causa 80 de dano gasta 50 de mana"//attack desc
nums[i++] = 50;//type cost
nums[i++] = 2;//colorless cost
nums[i++] = 80;//damage
strings[j++] = "ATIVO";//attack 2
strings[j++] = "Ativa: Começa os turnos com 10 de vida a mais por ser valente.";//attack 2 desc
nums[i++] = 10;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "Passiva ";//attack 3
strings[j++] = "Passiva : Seus buff custam 10 de mana a menos.";//attack 3 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//weakness
strings[j++] = "\0";//resistance
nums[i++] = 3;//retreate cost
nums[i++] = 4;//rarity


nums[i++] = ++z;//card number
strings[j++] = "Joe o Guerreiro";//name
nums[i++] = 2;//stage
strings[j++] = "Guerreiro";//type
nums[i++] = 180;//hp
strings[j++] = "ATAQUE: ESPADA ";//attack 1
strings[j++] = "  O guerreiro pega sua espada e avança no oponente  e causa 100 de dano gasta 100 de mana"//attack desc
nums[i++] = 100;//type cost
nums[i++] = 2;//colorless cost
nums[i++] = 100;//damage
strings[j++] = "ATIVO";//attack 2
strings[j++] = "Ativa: Começa os turnos com 10 de vida a mais por ser valente.";//attack 2 desc
nums[i++] = 10;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "Passiva ";//attack 3
strings[j++] = "Passiva : Seus buff custam 10 de mana a menos.";//attack 3 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//weakness
strings[j++] = "\0";//resistance
nums[i++] = 3;//retreate cost
nums[i++] = 4;//rarity


nums[i++] = ++z;//card number
strings[j++] = "Joe o Guerreiro";//name
nums[i++] = 2;//stage
strings[j++] = "Guerreiro";//type
nums[i++] = 180;//hp
strings[j++] = "ATAQUE: FORÇA DE VONTADE ";//attack 1
strings[j++] = "  O guerreiro se prepara para  avançar no oponente  e causa 15 de dano gasta 5 de mana. O próximo ataque causará 20 de dano a mais"//attack desc
nums[i++] = 5;//type cost
nums[i++] = 2;//colorless cost
nums[i++] = 15;//damage
strings[j++] = "ATIVO";//attack 2
strings[j++] = "Ativa: Começa os turnos com 10 de vida a mais por ser valente.";//attack 2 desc
nums[i++] = 10;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "Passiva ";//attack 3
strings[j++] = "Passiva : Seus buff custam 10 de mana a menos.";//attack 3 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//weakness
strings[j++] = "\0";//resistance
nums[i++] = 3;//retreate cost
nums[i++] = 4;//rarity

nums[i++] = ++z;//card number
strings[j++] = "BUFF: JÁ PASSEI POR ISSO";//name
nums[i++] = 2;//stage
strings[j++] = "BUFF GUERREIRO";//type
nums[i++] = 0;//hp
strings[j++] = "\0";//attack 1
strings[j++] = "O guerreiro já passou por tantas batalhas que sabe como se preparar. Começa os 3 turnos com mais 20 de vida.";//attack desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//attack 2
strings[j++] = "\0";//attack 2 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//attack 3
strings[j++] = "\0";//attack 3 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//weakness
strings[j++] = "\0";//resistance
nums[i++] = 0;//retreate cost
nums[i++] = 3;//rarity

nums[i++] = ++z;//card number
strings[j++] = "BUFF: MELHORES AMIGOS";//name
nums[i++] = 2;//stage
strings[j++] = "BUFF GUERREIRO";//type
nums[i++] = 0;//hp
strings[j++] = "\0";//attack 1
strings[j++] = "O guerreiro e seu cavalo estão sempre juntos toda vez que essa carta for apresentada. O guerreiro ganha 50 de mana.";//attack desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//attack 2
strings[j++] = "\0";//attack 2 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//attack 3
strings[j++] = "\0";//attack 3 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//weakness
strings[j++] = "\0";//resistance
nums[i++] = 0;//retreate cost
nums[i++] = 3;//rarity


nums[i++] = ++z;//card number
strings[j++] = "BUFF: CONFIANÇA";//name
nums[i++] = 2;//stage
strings[j++] = "BUFF GUERREIRO";//type
nums[i++] = 0;//hp
strings[j++] = "\0";//attack 1
strings[j++] = "O guerreiro sente-se extremamente confiante e seus próximos ataques irão dar mais 10 de dano";//attack desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//attack 2
strings[j++] = "\0";//attack 2 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//attack 3
strings[j++] = "\0";//attack 3 desc
nums[i++] = 0;//type cost
nums[i++] = 0;//colorless cost
nums[i++] = 0;//damage
strings[j++] = "\0";//weakness
strings[j++] = "\0";//resistance
nums[i++] = 0;//retreate cost
nums[i++] = 3;//rarity
*/
//CARTAS DE MANA A ABAIXO






}